{% set name = "pymirc" %}
{% set version = "0.29" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymirc-{{ version }}.tar.gz
  sha256: c7d5bb99aef06989c225ec9381c061e1757a6fc61011b5a31d5ad961b81becdb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
    - setuptools_scm_git_archive
  run:
    - matplotlib-base >=2.2.2
    - nibabel >=3.0
    - numba >=0.39
    - numpy >=1.15
    - pydicom >=1.1
    - python >=3.6
    - scikit-image >=0.14
    - scipy >=1.1

test:
  imports:
    - pymirc
    - pymirc.fileio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gschramm/pymirc
  summary: Python imaging utilities developed in the medical imaging research center of KU Leuven
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gschramm
